import { IconsNamesMapType } from "./types";
import {
  Google,
  Apple,
  Home,
  Search,
  Settings,
  ChevronRight,
  ArrowRight,
  TrendingUp,
  Selector,
  Wallet,
  Deposit,
  Transfer,
  Withdraw,
  Send,
  Share,
  Solana,
  BaseStatus,
  TrendingDown,
  Twitter,
  Message,
  FileDownload,
} from "./Icons";

export const IconsMap: IconsNamesMapType = {
  google: Google,
  apple: Apple,
  home: Home,
  search: Search,
  settings: Settings,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  trendingUp: TrendingUp,
  selector: Selector,
  wallet: Wallet,
  deposit: Deposit,
  transfer: Transfer,
  withdraw: Withdraw,
  send: Send,
  share: Share,
  solana: Solana,
  baseStatus: BaseStatus,
  trendingDown: TrendingDown,
  twitter: Twitter,
  message: Message,
  fileDownload: FileDownload,
};
