name: Deploy MOONSHOT to VPS (PROD)

on: workflow_dispatch

env:
  BRANCH: prod
  
jobs:
  Update-server:
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes in prod server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd ${{ vars.PROD_PATH_TO_DEPLOY }}
            branch=$(git rev-parse --abbrev-ref HEAD)   # chech current branch
            echo "Current branch is $branch"
            if [[ "$branch" != "${{ env.BRANCH }}" ]]; then           
              git checkout ${{ env.BRANCH }}
            fi
            git fetch --all
            git reset --hard origin/${{ env.BRANCH }}
            git pull

      - name: Install frontend deps in prod server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd ${{ vars.PROD_PATH_TO_DEPLOY }}/frontend
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install --legacy-peer-deps

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Run build task
        run: |
          cd frontend
          npm run build --if-present

      - name: Delete previos build in server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            # cd ${{ vars.PROD_PATH_TO_DEPLOY }}/frontend
            if [ -d '${{ vars.PROD_PATH_TO_DEPLOY }}/frontend/build' ]; then
              echo "Build finded! EXTERMINATE!!!!"
              rm -rf ${{ vars.PROD_PATH_TO_DEPLOY }}/frontend/build
            else
              echo "Build not exist. Continue working"
            fi

      - name: Deploy Build to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          source: 'frontend/.next,frontend/public'
          target: ${{ vars.PROD_PATH_TO_DEPLOY }}

  Restart-PM2-service:
    runs-on: ubuntu-latest
    needs: [build-frontend, Update-server]
    steps:
      - name: Restart PM2 service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ vars.PROD_PATH_TO_DEPLOY }}
            echo "Restart service"
            pm2 restart ecosystem.config.js --only prod.frontend.moonshot.tech